### ISSUE TITLE
Checklist РК 1

### ISSUE THREAD

**Issue by edward-grolsh** [frontend-park-mail-ru/2017_2_Chunk#4]
- [ ]     Ваше приложение задеплоено на heroku
- [ ]     Страницы приложения переключаются без перезагрузки сайта (то есть ваше приложение — это SPA)
- [ ]     Выполнена интеграция с бекендом
- [ ]     Используется модульный и компонентный подход, используются шаблонизаторы
- [ ]     Есть формы авторизации и регистрации с валидацией данных
- [ ]     Есть линтер, который не ругается на ваш код
- [ ]     API вашего приложения правильно составлено и задокументировано, в модулях вашего приложения также присутствует JSDoc-документация
- [ ]     В приложении присутствует кросс-доменное взаимодействие и правильно настроен CORS
